repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.14
    hooks:
    - id: ruff-check
      name: ruff lint
    - id: ruff-check
      name: ruff isort
      args: [--select, I, --fix]
    - id: ruff-format
